# yaml-language-server: $schema=https://json.schemastore.org/eslintrc

ignorePatterns:
  # Ignore build outputs
  - "**/dist"
  - "**/cdk.out"

  # Ignore plain JS
  - "**/*.js"
  - "**/*.jsx"

  - "**/*.d.ts"

overrides:
  # TypeScript
  - files: ["*.ts", "*.tsx", "*.mts"]
    extends:
      - eslint:recommended

      - plugin:@typescript-eslint/recommended-type-checked
      - plugin:@typescript-eslint/stylistic-type-checked

      - plugin:jsdoc/recommended-typescript-error

      # Prettier for formatting, should be applied last
      - plugin:prettier/recommended

    plugins:
      # Manually register eslint-plugin-import rather than extending the plugin:import/recommended
      # and plugin:import/typescript configurations. We only care about the sorting rules, and not
      # bringing in all the recommended rules keeps linting nice and fast.
      - import

    parserOptions:
      project: ./tsconfig.json

    rules:
      "prettier/prettier":
        - error
        - singleQuote: true
          semi: false

      # Prefer type imports/exports
      "@typescript-eslint/consistent-type-imports": error
      "@typescript-eslint/consistent-type-exports": error

      "@typescript-eslint/consistent-type-definitions":
        - error
        - 'type'

      # Allow `${number}`
      "@typescript-eslint/restrict-template-expressions":
        - error
        - allowNumber: true

      # Only require jsdoc on exports
      # "jsdoc/require-jsdoc":
      #   - error
      #   - publicOnly: true
      "jsdoc/require-jsdoc": off

      # Require a blank line between description and other tags
      "jsdoc/tag-lines":
        - error
        - any
        - startLines: 1

      # Alphabetically sort imports, and include a blank line between groups
      "import/order":
        - error
        - alphabetize:
            caseInsensitive: true
            order: asc
          newlines-between: always

      # Make sure imports are at the top of the file
      "import/first": error

      # https://typescript-eslint.io/rules/switch-exhaustiveness-check
      "@typescript-eslint/switch-exhaustiveness-check":
        - error
        - considerDefaultExhaustiveForUnions: true
          requireDefaultForNonUnion: true

  # # Jest
  # - files: ["*.test.ts", "*.test.tsx"]
  #   extends:
  #     - plugin:jest/recommended
  #     - plugin:jest/style
